### PR TITLE
Auto create audit table

### LINKED ISSUE #52: [BUG] - BigQuery - Missing `audit` table when using a custom sink name
## Description
When I set a custom audit sink name using COMET_AUDIT_SINK_NAME, the `audit` table is missing.
I am running load jobs on Google BigQuery

## Expected behavior
The job should insert in the two audit tables `audit` and `rejected`

## Current Behavior
`audit` table is no longer created/populated. Check the attached screenshot for a more visual illustration of the current behaviour

missing_audit_table

## Steps to reproduce
1. Run a Load into a BigQuery table
2. Make sure you have both tables (`audit` and `rejected`) with data in them
3. Set the variable COMET_AUDIT_SINK_NAME to `custom_audit`
4. Make sure you have created the  `custom_audit` dataset in you BigQuery project
5. Run the same Load as in (1)
6. See that the audit table is missing the `custom_audit` dataset

## Context
GCP - BigQuery - 
# Life cycle

## Possible implementation
TBD

## Complexity estimation
TBD

### PR DESCRIPTION
**Pull request by hayssams**
## Summary

**Related Issue: #52**

**PR Type: Bug Fix**

**Status: Ready to review**

**Breaking change? No**

### CODE REVIEW

File: src/main/scala/com/ebiznext/comet/job/index/bqload/BigQueryNativeJob.scala [hunk 1]
```diff
@@ -127,6 +127,26 @@ class BigQueryNativeJob(
...
+          bigquery.create(tableInfo)
+          logger.info(s"Table $datasetName.$tableName created successfully")
+      }
+    } match {
+      case Success(_) =>
+      case Failure(e) =>
+        logger.info(s"Table $datasetName.$tableName was not created.")
+        Utils.logException(logger, e)
+    }
+  }
```
Comment (abdelhakimbendjabeur) [inline src/main/scala/com/ebiznext/comet/job/index/bqload/BigQueryNativeJob.scala:149]: Why did it become necessary to create the table after changing the dataset name, how was it created before?
